server.port=8082
spring.application.name=finance-service

spring.datasource.url=${DB_URL:jdbc:postgresql://10.23.240.38:5432/indr_aug13_smartsavingsandinvestment_dev?connectTimeout=5}
spring.datasource.username=${DB_USERNAME:indr_aug13_smartsavingsandinvestment_dev}
spring.datasource.password=${DB_PASSWORD:TCS@123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jackson.serialization.write-dates-as-timestamps=false

auth-service.url=${AUTH_SERVICE_URL:http://localhost:8081}
microvault.internal.token=${INTERNAL_TOKEN:microvault-local}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persistAuthorization=true
